/**
 * Seed Script — Import existing verified events into Supabase
 * 
 * Run: node scripts/seed-events.js
 * 
 * Requires: SUPABASE_URL and SUPABASE_SERVICE_KEY env vars
 */

import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY;

if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
  console.error('Set SUPABASE_URL and SUPABASE_SERVICE_KEY environment variables');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

// Existing verified events from v1
const SEED_EVENTS = [
  { title: "Friday Connections: Multi-Chamber Networking", organizer: "ChamberWest / SSL Chamber / Murray Chamber", date: "2026-04-17", time: "8:00 AM – 9:30 AM", location: "West Valley City", venue: "Rotating venues across SL County", region: "Salt Lake County", category: "Chamber", industry: "General Business", cost: "Free", recurring: true, recurrence_note: "3rd Friday of every month", url: "https://www.chamberwest.com/friday-connections-networking-event/", description: "Speed networking across multiple chambers. Meet professionals from ChamberWest, South Salt Lake, Murray Area, and Utah Pacific Islander chambers.", source: "manual" },
  { title: "Business Women's Forum — Spring Mixer", organizer: "Salt Lake Chamber", date: "2026-04-14", time: "11:30 AM – 1:00 PM", location: "Salt Lake City", venue: "Salt Lake Chamber, 175 E 400 S", region: "Salt Lake County", category: "Professional Development", industry: "General Business", cost: "Paid", recurring: true, recurrence_note: "Monthly", url: "https://business.slchamber.com/events/details/business-women-s-forum-2026-spring-mixer-15862", description: "Monthly forum empowering women in business through leadership panels, networking, and skill-building workshops.", source: "manual" },
  { title: "CONNECT Utah STG Weekly Networking", organizer: "CONNECT Utah", date: "2026-03-26", time: "11:30 AM – 1:00 PM", location: "St. George", venue: "600 S Medical Center Dr, St. George", region: "Southern Utah", category: "Networking Mixer", industry: "General Business", cost: "Free", recurring: true, recurrence_note: "Every Wednesday", url: "https://435locals.com/event/connect-utah-stg-4/", description: "Drop-in weekly networking in Southern Utah. No RSVP needed — just bring business cards.", source: "manual" },
  { title: "CEO of the Year Awards", organizer: "Utah Business Magazine", date: "2026-03-31", time: "11:00 AM", location: "Salt Lake City", venue: "The Grand America Hotel", region: "Salt Lake County", category: "Speaker Event", industry: "General Business", cost: "Paid", recurring: false, url: "https://www.utahbusiness.com/ceo-of-the-year/", description: "Annual awards honoring Utah CEOs who have led their organizations with strength, courage, and endurance.", source: "manual" },
  { title: "Start School with Adam Edmunds", organizer: "Silicon Slopes", date: "2026-04-03", time: "12:00 PM – 1:00 PM", location: "Lehi", venue: "Silicon Slopes HQ, 2600 W Executive Pkwy", region: "Utah County", category: "Speaker Event", industry: "Startups & Entrepreneurship", cost: "Free", recurring: true, recurrence_note: "Weekly/biweekly speakers", url: "https://www.siliconslopes.com/events", description: "Start School speaker series at Silicon Slopes HQ. Hear from founders building real businesses.", source: "manual" },
  { title: "Founder Friday: Gavin Christensen (Kickstart)", organizer: "Utah Business Magazine", date: "2026-04-24", time: "9:00 AM", location: "Lehi", venue: "Kiln Coworking, Lehi", region: "Utah County", category: "Speaker Event", industry: "Startups & Entrepreneurship", cost: "Paid", recurring: true, recurrence_note: "Monthly", url: "https://www.utahbusiness.com/founder-friday/", description: "Fireside chat with Gavin Christensen, founder of Kickstart.", source: "manual" },
  { title: "Women to Watch Awards", organizer: "Utah Business Magazine", date: "2026-05-20", time: "TBA", location: "Salt Lake City", venue: "The Grand America Hotel", region: "Salt Lake County", category: "Conference", industry: "General Business", cost: "Paid", recurring: false, url: "https://www.utahbusiness.com/30-women-to-watch/", description: "Spotlight on women carving out legacies and paving the way for the next generation of female leaders.", source: "manual" },
  { title: "Founder Friday: Ryan Anderson (Filevine)", organizer: "Utah Business Magazine", date: "2026-05-22", time: "9:00 AM", location: "Lehi", venue: "Kiln Coworking, Lehi", region: "Utah County", category: "Speaker Event", industry: "Startups & Entrepreneurship", cost: "Paid", recurring: true, recurrence_note: "Monthly", url: "https://www.utahbusiness.com/founder-friday/", description: "Fireside chat with Ryan Anderson, founder of Filevine.", source: "manual" },
  { title: "Executive Excellence Awards", organizer: "Utah Business Magazine", date: "2026-06-23", time: "TBA", location: "Salt Lake City", venue: "David Eccles School of Business", region: "Salt Lake County", category: "Conference", industry: "General Business", cost: "Paid", recurring: false, url: "https://www.utahbusiness.com/executive-excellence/", description: "Honoring executive team members whose vision and expertise are vital to company growth.", source: "manual" },
  { title: "Innovation Awards Summit", organizer: "Utah Business Magazine", date: "2026-09-02", time: "8:30 AM – 1:00 PM", location: "West Valley City", venue: "Utah Cultural Celebration Center", region: "Salt Lake County", category: "Conference", industry: "Technology", cost: "Paid", recurring: false, url: "https://www.utahbusiness.com/innovation-awards/", description: "Statewide celebration of problem-solving, creativity, and technology.", source: "manual" },
  { title: "Best Companies to Work For Awards", organizer: "Utah Business Magazine", date: "2026-12-10", time: "TBA", location: "Salt Lake City", venue: "The Grand America Hotel", region: "Salt Lake County", category: "Conference", industry: "General Business", cost: "Paid", recurring: false, url: "https://www.utahbusiness.com/best-companies-to-work-for/", description: "Recognizing Utah's premier employers as rated by their own workforce.", source: "manual" },
  { title: "Cache Valley Women in Business Luncheon", organizer: "Cache Valley Chamber of Commerce", date: "2026-04-08", time: "11:30 AM – 1:00 PM", location: "Logan", venue: "TBA, Logan", region: "Cache County", category: "Chamber", industry: "General Business", cost: "Paid", recurring: false, url: "https://business.cachechamber.com/events/details/women-in-business-luncheon-04-08-2026-37022", description: "Cache Valley Chamber luncheon for women in business in Logan.", source: "manual" },
  { title: "Women Tech Awards Luncheon", organizer: "Women Tech Council", date: "2026-10-02", time: "11:00 AM – 1:30 PM", location: "Salt Lake City", venue: "The Grand America Hotel", region: "Salt Lake County", category: "Conference", industry: "Technology", cost: "Paid", recurring: false, url: "https://www.womentechcouncil.com/awards/", description: "Annual awards recognizing women driving innovation in tech.", source: "manual" },
  { title: "SCORE Start SMART Workshop", organizer: "SCORE Utah", date: "2026-03-23", time: "10:00 AM – 12:00 PM", location: "Salt Lake City", venue: "Innovation Center, SLC", region: "Salt Lake County", category: "Workshop", industry: "Small Business", cost: "Free", recurring: true, recurrence_note: "Monthly", url: "https://www.score.org/utah/event/start-smart-workshop-own-your-own-business", description: "Free workshop answering basic business start-up questions.", source: "manual" },
  { title: "Tourism Business Development Workshop", organizer: "Utah Office of Tourism", date: "2026-04-22", time: "All Day (Apr 22-23)", location: "Kanab", venue: "Kanab Center", region: "Southern Utah", category: "Workshop", industry: "Hospitality & Tourism", cost: "Free", recurring: false, url: "https://travel.utah.gov/workshop/", description: "Two-day state-sponsored workshop on tourism business development.", source: "manual" },
  { title: "Open edX Conference 2026", organizer: "Open edX / WGU", date: "2026-05-19", time: "All Day (May 19-22)", location: "Salt Lake City", venue: "Little America Hotel, 500 S Main St", region: "Salt Lake County", category: "Conference", industry: "Education & Training", cost: "Paid", recurring: false, url: "https://www.eventbrite.com/e/open-edx-conference-2026-tickets-1967626286189", description: "Global conference for educators, developers, and innovators.", source: "manual" },
  { title: "Impactful™ Business Networking", organizer: "Impactful Networking", date: "2026-04-02", time: "6:00 PM – 8:00 PM", location: "Salt Lake City", venue: "TBA, Salt Lake City", region: "Salt Lake County", category: "Networking Mixer", industry: "General Business", cost: "Paid", recurring: true, recurrence_note: "Monthly", url: "https://www.eventbrite.com/e/impactfultm-business-networking-tickets-1984733256598", description: "Monthly business networking event in Salt Lake City.", source: "manual" },
  { title: "Business Networking 1-Day Workshop", organizer: "LearneRRing", date: "2026-04-10", time: "9:00 AM – 5:00 PM", location: "Multiple Utah locations", venue: "SLC, West Valley, St. George, Provo, West Jordan", region: "Salt Lake County", category: "Workshop", industry: "Professional Development", cost: "Paid", recurring: true, recurrence_note: "Apr 10, May 8, Jun 12, Jul 10", url: "https://www.eventbrite.com/e/business-networking-1-day-workshop-salt-lake-city-ut-tickets-1931673008969", description: "Full-day workshop on strategic networking skills at locations across Utah.", source: "manual" },
  { title: "Salt Lake City Career Fair", organizer: "Various Organizers", date: "2026-04-15", time: "10:00 AM – 2:00 PM", location: "Salt Lake City", venue: "TBA, Salt Lake City", region: "Salt Lake County", category: "Conference", industry: "General Business", cost: "Free", recurring: false, url: "https://www.eventbrite.com/e/salt-lake-city-career-fair-tickets-909388333987", description: "Career fair connecting job seekers with employers across multiple industries.", source: "manual" },
  { title: "NIAX March Social — Midvale", organizer: "NIAX", date: "2026-03-27", time: "5:30 PM – 7:30 PM", location: "Midvale", venue: "TBA, Midvale", region: "Salt Lake County", category: "Networking Mixer", industry: "General Business", cost: "Paid", recurring: true, recurrence_note: "Monthly", url: "https://allevents.in/midvale/niax-march-social-midvale/100001984012703404", description: "NIAX monthly social networking event in Midvale.", source: "manual" },
  { title: "NIAX Next Level Networking — Sandy", organizer: "NIAX", date: "2026-04-10", time: "3:30 PM – 5:00 PM", location: "Sandy", venue: "TBA, Sandy", region: "Salt Lake County", category: "Networking Mixer", industry: "General Business", cost: "Paid", recurring: true, recurrence_note: "Monthly", url: "https://allevents.in/sandy/niax-next-level-networking/100001985631988730", description: "Structured, relationship-driven networking in Sandy.", source: "manual" },
  { title: "NIAX Next Level Networking — Farmington", organizer: "NIAX", date: "2026-04-17", time: "3:30 PM – 5:00 PM", location: "Farmington", venue: "TBA, Farmington", region: "Davis County", category: "Networking Mixer", industry: "General Business", cost: "Paid", recurring: true, recurrence_note: "Monthly", url: "https://allevents.in/farmington/niax-next-level-networking/100001985595836598", description: "Structured networking in Davis County.", source: "manual" },
  { title: "2026 Pillar of the Valley", organizer: "Utah Valley Chamber of Commerce", date: "2026-04-14", time: "7:00 PM – 9:00 PM", location: "Provo", venue: "Utah Valley Convention Center, 220 W Center St", region: "Utah County", category: "Speaker Event", industry: "General Business", cost: "Paid", recurring: false, url: "https://thechamber.org/resources/events/", description: "Utah Valley Chamber annual Pillar of the Valley awards event.", source: "manual" },
  { title: "2026 Chamber Golf Classic", organizer: "Utah Valley Chamber of Commerce", date: "2026-09-14", time: "7:00 AM – 2:00 PM", location: "Provo", venue: "Riverside Country Club, 2701 N University Ave", region: "Utah County", category: "Networking Mixer", industry: "General Business", cost: "Paid", recurring: false, url: "https://thechamber.org/resources/events/", description: "Annual golf tournament and networking day for Utah Valley business leaders.", source: "manual" },
  { title: "2026 Executive Summits", organizer: "Utah Valley Chamber of Commerce", date: "2026-10-23", time: "7:00 AM – 3:00 PM", location: "Sundance", venue: "Sundance Mountain Resort, 8841 Alpine Loop Scenic Byway", region: "Utah County", category: "Conference", industry: "General Business", cost: "Paid", recurring: false, url: "https://thechamber.org/resources/events/", description: "Full-day executive summit at Sundance Mountain Resort.", source: "manual" },
  { title: "2026 Growth & Prosperity Summit", organizer: "Utah Valley Chamber of Commerce", date: "2026-11-12", time: "8:00 AM – 2:00 PM", location: "Orem", venue: "Utah Valley University, Sorensen Center Ballroom", region: "Utah County", category: "Conference", industry: "General Business", cost: "Paid", recurring: false, url: "https://thechamber.org/resources/events/", description: "Annual growth and prosperity summit at UVU.", source: "manual" },
  { title: "Founders Space: Quick Connects & Beers", organizer: "Silicon Slopes", date: "2026-03-25", time: "8:00 AM – 8:30 AM", location: "Virtual", venue: "Virtual (Silicon Slopes)", region: "Salt Lake County", category: "Networking Mixer", industry: "Startups & Entrepreneurship", cost: "Free", recurring: true, recurrence_note: "Every Tuesday", url: "https://www.siliconslopes.com/events", description: "Quick 30-minute virtual networking every Tuesday morning.", source: "manual" },
  { title: "BSidesSLC Security Conference", organizer: "BSidesSLC", date: "2026-04-09", time: "8:00 AM – 5:00 PM", location: "Salt Lake City", venue: "TBA, Salt Lake City", region: "Salt Lake County", category: "Conference", industry: "Technology", cost: "Paid", recurring: false, url: "https://www.siliconslopes.com/events", description: "Two-day information security conference (Apr 9-10).", source: "manual" },
  { title: "Vibe Code Club for Entrepreneurs", organizer: "Silicon Slopes", date: "2026-04-07", time: "11:30 AM – 1:00 PM", location: "Salt Lake City", venue: "TBA, Salt Lake City", region: "Salt Lake County", category: "Workshop", industry: "Technology", cost: "Free", recurring: true, recurrence_note: "Biweekly", url: "https://www.siliconslopes.com/events", description: "Hands-on coding club for entrepreneurs at Silicon Slopes.", source: "manual" },
  { title: "Silicon Slopes Military Chapter Mixer", organizer: "Silicon Slopes Military Chapter", date: "2026-04-21", time: "6:00 PM – 7:30 PM", location: "Lehi", venue: "TBA, Lehi", region: "Utah County", category: "Networking Mixer", industry: "General Business", cost: "Free", recurring: false, url: "https://www.siliconslopes.com/events", description: "Networking mixer for military-connected professionals.", source: "manual" },
  { title: "Utah HIMSS Annual Conference", organizer: "HIMSS Utah Chapter", date: "2026-04-24", time: "8:00 AM – 5:00 PM", location: "Salt Lake City", venue: "TBA, Salt Lake City", region: "Salt Lake County", category: "Conference", industry: "Healthcare", cost: "Paid", recurring: false, url: "https://www.siliconslopes.com/events", description: "Annual healthcare IT conference with local Utah HealthTech companies.", source: "manual" },
  { title: "Red Rock Data Science Conference 2026", organizer: "Red Rock Data Science", date: "2026-05-18", time: "9:00 AM – 3:00 PM", location: "Salt Lake City", venue: "TBA, Salt Lake City", region: "Salt Lake County", category: "Conference", industry: "Technology", cost: "Paid", recurring: false, url: "https://www.siliconslopes.com/events", description: "Multi-day data science conference (May 18-21).", source: "manual" },
  { title: "STACKED IT & Security Summit", organizer: "STACKED", date: "2026-09-10", time: "8:00 AM – 5:00 PM", location: "Salt Lake City", venue: "TBA, Salt Lake City", region: "Salt Lake County", category: "Conference", industry: "Technology", cost: "Paid", recurring: false, url: "https://www.siliconslopes.com/events", description: "Full-day IT and security summit.", source: "manual" },
];

async function seed() {
  console.log(`Seeding ${SEED_EVENTS.length} events...`);

  for (const event of SEED_EVENTS) {
    const { data, error } = await supabase
      .from('events')
      .insert({ ...event, is_active: true })
      .select();

    if (error) {
      console.error(`  Error: "${event.title}" — ${error.message}`);
    } else {
      console.log(`  ✓ ${event.title}`);
    }
  }

  console.log('\nDone seeding!');
}

seed().catch(console.error);
